runtime: python39

env_variables:
  DJANGO_SETTINGS_MODULE: "bank_parser.settings"
  DEBUG: "False"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "money_tracking"
  DB_USER: "postgres"
  DB_PASSWORD: "your-secure-password"
  DB_HOST: "/cloudsql/your-project:region:instance-name"
  DB_PORT: "5432"

handlers:
  - url: /static
    static_dir: staticfiles/
    secure: always

  - url: /media
    static_dir: media/
    secure: always

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
