# Generated by Django 5.2.5 on 2025-08-31 19:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('source_file', models.FileField(upload_to='statements/')),
                ('account_number', models.CharField(max_length=50)),
                ('account_abbr', models.CharField(max_length=20)),
                ('statement_from_date', models.DateField()),
                ('statement_to_date', models.DateField()),
                ('statement_type', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('TXT', 'Text'), ('OTHER', 'Other')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-statement_to_date'],
            },
        ),
        migrations.CreateModel(
            name='StatementDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statementdetail_set', to='statements.statement')),
            ],
            options={
                'verbose_name': 'Statement Detail',
                'verbose_name_plural': 'Statement Details',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
