# Generated by Django 5.2.5 on 2025-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='statements/'),
        ),
    ]
