# Generated by Django 5.2.5 on 2025-09-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_alter_statement_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
