# Generated by Django 5.2.5 on 2025-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_alter_statement_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementdetail',
            name='direction',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=6),
        ),
    ]
