# Generated by Django 4.2.24 on 2025-09-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_alter_statementdetail_direction'),
    ]

    operations = [
    ]
