# Generated by Django 4.2.24 on 2025-09-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_auto_20250906_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_abbr', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('INVESTMENT', 'Investment'), ('BANK', 'Bank')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['bank_name', 'account_abbr'],
            },
        ),
        migrations.RemoveField(
            model_name='statement',
            name='account_abbr',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='statements.account'),
        ),
    ]
