# Generated by Django 4.2.24 on 2025-09-06 17:10

from django.db import migrations


def create_default_accounts(apps, schema_editor):
    """Create default accounts for existing statements"""
    Account = apps.get_model('statements', 'Account')
    Statement = apps.get_model('statements', 'Statement')
    
    # Create a default account for existing statements
    default_account, created = Account.objects.get_or_create(
        account_abbr='DEFAULT',
        defaults={
            'bank_name': 'Unknown Bank',
            'account_number': '000000000',
            'account_type': 'BANK'
        }
    )
    
    # Update all existing statements to use the default account
    Statement.objects.filter(account__isnull=True).update(account=default_account)


def reverse_create_default_accounts(apps, schema_editor):
    """Reverse the data migration"""
    # No need to do anything as we're not removing data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0006_account_remove_statement_account_abbr_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_accounts, reverse_create_default_accounts),
    ]
