# Generated by Django 4.2.24 on 2025-09-07 04:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0008_auto_20250906_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_cost', models.DecimalField(decimal_places=2, help_text='The original cost basis of the investment', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('market_value', models.DecimalField(decimal_places=2, help_text='The current market value of the investment', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(help_text='Date of the investment valuation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_data', to='statements.account')),
            ],
            options={
                'verbose_name': 'Investment Data',
                'verbose_name_plural': 'Investment Data',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
