# Generated by Django 4.2.24 on 2025-09-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0009_investmentdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investment Data', 'verbose_name_plural': 'Investment Data'},
        ),
        migrations.RemoveField(
            model_name='investmentdata',
            name='date',
        ),
    ]
