# Generated by Django 4.2.24 on 2025-09-07 14:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0010_alter_investmentdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current value/balance of the account', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='When this value was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_values', to='statements.account')),
            ],
            options={
                'verbose_name': 'Account Value',
                'verbose_name_plural': 'Account Values',
                'ordering': ['-date_updated'],
                'unique_together': {('account', 'date_updated')},
            },
        ),
    ]
