# Generated by Django 4.2.24 on 2025-09-09 01:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0011_accountvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvalue',
            name='booking_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Booking value for investment accounts (original cost basis)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
