# Generated by Django 4.2.24 on 2025-09-25 00:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0012_accountvalue_booking_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvalue',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current value/balance of the account', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
