# Generated by Django 4.2.24 on 2025-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0014_alter_statement_type_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_from_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_to_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_type',
            field=models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('TXT', 'Text'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statement',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='statementdetail',
            name='direction',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='statementdetail',
            name='item',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='statementdetail',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['account', '-statement_to_date'], name='statements__account_a57a06_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['-uploaded_at'], name='statements__uploade_4edc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['statement_from_date', 'statement_to_date'], name='statements__stateme_e3cbad_idx'),
        ),
        migrations.AddIndex(
            model_name='statementdetail',
            index=models.Index(fields=['statement', '-transaction_date'], name='statements__stateme_536add_idx'),
        ),
        migrations.AddIndex(
            model_name='statementdetail',
            index=models.Index(fields=['transaction_date', 'direction'], name='statements__transac_9807d4_idx'),
        ),
        migrations.AddIndex(
            model_name='statementdetail',
            index=models.Index(fields=['direction', 'amount'], name='statements__directi_b3293a_idx'),
        ),
    ]
