# Generated by Django 4.2.24 on 2025-11-29 21:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statements', '0016_add_date_field_to_accountvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('TFSA', 'TFSA'), ('RRSP', 'RRSP')], help_text='Type of registered account', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Contribution amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date of contribution')),
                ('tax_year', models.CharField(choices=[('current', 'Current Year'), ('previous', 'Previous Year')], default='current', help_text='Tax year this contribution applies to (for RRSP first 60 days)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made this contribution', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('TFSA', 'TFSA'), ('RRSP', 'RRSP')], help_text='Type of registered account', max_length=10)),
                ('limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Contribution room limit for this account type', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_year', models.IntegerField(help_text='Tax year this limit applies to (e.g., 2025)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contribution_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution Room',
                'verbose_name_plural': 'Contribution Rooms',
                'ordering': ['user', 'tax_year', 'account_type'],
                'unique_together': {('user', 'account_type', 'tax_year')},
            },
        ),
    ]
