name: Deploy with Cloud Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: money-tracking
  REGION: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Django checks
      run: |
        python manage.py check
        python manage.py check --deploy
    
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput --dry-run

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Deploy with Cloud Build
      run: |
        gcloud builds submit --config deployment/cloudbuild.yaml .
    
    - name: Run Database Migrations
      run: |
        # Create a Cloud Run job for migrations
        gcloud run jobs create migrate-db-$GITHUB_SHA \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --region $REGION \
          --set-env-vars="DJANGO_SETTINGS_MODULE=bank_parser.settings,DEBUG=False,DB_ENGINE=django.db.backends.postgresql,DB_NAME=money_tracking,DB_USER=postgres,DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=/cloudsql/$PROJECT_ID:$REGION:money-tracking-db,DB_PORT=5432" \
          --add-cloudsql-instances=$PROJECT_ID:$REGION:money-tracking-db \
          --command="python" \
          --args="manage.py,migrate" \
          --max-retries=3 \
          --parallelism=1 \
          --task-count=1
        
        gcloud run jobs execute migrate-db-$GITHUB_SHA --region $REGION --wait
        
        # Clean up the job
        gcloud run jobs delete migrate-db-$GITHUB_SHA --region $REGION --quiet
    
    - name: Show Service URL
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')
        echo "Service deployed at: $SERVICE_URL"
        echo "::notice title=Deployment Complete::Your app is available at $SERVICE_URL"
